### ISSUE TITLE
Incorrect degree sorting on gene rays

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#20]
The sorting of the genes on the "rays" of the layout are incorrect. My use cases are largely choosing a parameter set (ZmIonome > Fe57 > ZmRoot), sorting the gene list by local degee (descending) and then clicking the top genes. I'd expect the top ones to always highlight the gene closest to the SNP, but even the second case does not hold:
![screenshot from 2016-06-08 11-30-27](https://cloud.githubusercontent.com/assets/2566591/15902286/c95e829c-2d6c-11e6-9ad1-5e58467f2294.png)

GRMZM2G004699 is tied for highest local degree (37) but is second from the SNP to a gene that has a local degree of 8 (GRMZM2G325575). This is an issue because I want to cover the use case of finding highly local genes that are directly connected to other highly local genes (its neighbors being the closest gene to the SNP).

**Comment by monprin** [comment]
But those are on different SNPs, aren't they?

**Comment by schae234** [comment]
I see. They are organized differently than I expected. I thought it was 1 color parent SNP. But it's alternating colors to indicate change of parent SNP?

Can you think of a way to somehow get high degree SNPs to the center while still distinguishing genes from different SNPs? This idea of most likely (highest local degree) gene being near the center is a super powerful one. Clicking a gene and seeing that it has edges to other genes that are near the center of the circle is the use case. Ideally, the further away from the center of the circle, the less likely the gene is to be a true candidate gene.

**Comment by monprin** [comment]
Yes that is how it currently works, I can think about it some more, but at the moment those ideas seem to be contradictory, and I tried assigning a color to each SNP in a group but it got very messy very quickly. 

Ill try to play some more tomorrow after getting the neighbors table set up.

**Comment by monprin** [comment]
The solution to this has been described in #25, at least provisionally.
