### ISSUE TITLE
Gene local degree

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#25]
- [x] Use the cytoscape.js local degree function instead of the camoco method. Tables should be updated when the parameter changes. For example, if I load ZmIonome > ZmRoot > P31 and sort by local degree I see the top gene has a degree of 37 regardless of the edge cutoff that I specify.
- [x] Order the collapsed gene groups by the highest local degree. If a "ray" has multiple gene groups, the gene group with the gene with the highest degree should be closest to the SNP node.

**Comment by monprin** [comment]
DO you want the count to be based on visible edges, visible genes, or both? (I had to write a custom degree function anyway) also would you like the same logic applied to the highlighting algorithm?

**Comment by monprin** [comment]
I implemented it such that it is based on both (as an artifact of the fact that edges that are connected to an invisible node are made invisible), but left it so that the nodes that are connected but the edge is below the cutoff are still highlighted, which I feel provide interesting information.

**Comment by monprin** [comment]
Also initial filtering is done based on the over all ldegree, because otherwise you end up with the possibility of regression that just eliminates all nodes.

**Comment by monprin** [comment]
Done in #35

**Comment by schae234** [comment]
Hi Joe,

Sorry for the lag, I want it based on visible edges. Can you make sure that the edge count is consistent across the tables and the tooltip? 

e.g.: 
![screenshot from 2016-06-16 08-57-18](https://cloud.githubusercontent.com/assets/2566591/16109373/6dc98ae6-33a0-11e6-89da-5c87b80368c4.png)

This screenshot should have degree be 7 for both the table and the tooltip. Also, the node next to the selected node should not be highlighted (I set the edge filtering level to 4 instead of the default 3). The network should _only_ display information that is based off of the current filtering parameters. Does cytoscape.js really count unrendered edges in its local degree count? You can't just rely on the built in function?

**Comment by monprin** [comment]
Okay, and nope, degree is based on the edge data we send it, not the visibility of said edges, but it works with just keeping a data attribute with the cur_ldegree.

**Comment by schae234** [comment]
Perfect!
