### ISSUE TITLE
Gene Subnetwork Table

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#26]
- [x] Highlight clicked genes in the subnetwork table (differentiate between clicked vs. neighbors)
- [x] Add an event that identifies the gene in the network when a gene in the subnetwork table is clicked. It doesn't need to be permanent like clicking a gene in the full table but you should be able to quickly find genes in the network from the subnetwork table. Make it a color on click then remove the color on release
- [x] Add ability to export the subnetwork AND the full gene network tables to file
  - [x] Include the snp 2 gene mapping and other parameters as columns in the table
  - [x] Design this in a forward thinking way that will make it easy to save and load data from files in the future ...

**Comment by monprin** [comment]
Okay I did it as just a hover event, rather than a click, and I also integrated the qtip to help make it pop better. What do you mean by snp 2 gene mapping? But the window size and flank limit are both in the Table now for download. Let me know what else you'd like to see. I also just left the Columns as is in the subnetwork table for the time being, until we do the annotations thing.

**Comment by monprin** [comment]
All of this is added in #32 !

**Comment by schae234** [comment]
SNP2Gene mapping parameters are the WindowSize and FlankLimit, looks like you have them in there. qtip looks great, except when you scroll in the table it goes nuts because it tries to load the tooltip for every row you hover over ... not sure what to do about this. Thoughts?

**Comment by monprin** [comment]
Hmm chrome seems to handle this just fine but firefox doesn't, I'll look into fixes so that it is more robust on firefox.

**Comment by schae234** [comment]
Hardy har har har. Freedom isn't free Joe.

**Comment by monprin** [comment]
Let me know what you think of it when you get a chance to play with it, but I am leaving it as is unless we can come up with something else, the only thing I can think to try is to deactivate the trigger during scrolling, but that could be weird. Do you have any ideas?

**Comment by monprin** [comment]
#35  does this for the time being

**Comment by schae234** [comment]
This looks good. Pretty cool effect!
