### ISSUE TITLE
More informative bread crumbs

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#28]
Include gene count as well as FlankLimit/Window size in the bread crumb footer. It does not necessarily need to be incorporated in the '>' notation of the bread crumbs, more like a HUD. Make sure they are updated when you update the filtering parameters.

`ZmRoot > ZmIonome > Fe57 > 50kb/2 -------------------  59 genes : 475 interactions`

Like this ^^ but pretty :sparkles:

**Comment by monprin** [comment]
#35 adds this in.
