### ISSUE TITLE
Gene Annotation System

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#29]
# Description

We want to be able to include arbitrary annotation information into the subnetwork table. Create a system that loads annotation tables from a `~/.cob/` directory or some installed python path and that displays that information when a gene is loaded into the subnetwork tab.

Use Case:

> Rob wants to include functional annotations with his results so he generates a table that includes two columns, one for Gene name and the other for functional annotations. He puts this table in `~/.cob/annotations` which gets loaded when cob is started. He moves to the browser and loads a dataset. He clicks a gene that has 3 neighbors and wants to know what the neighbors do so he finds the subnetwork tab. He sees that one of the neighbors has a functional annotation that he likes so he orders pizza to celebrate :pizza: . 

Lets start with simple logic of using gene names as keys ( we will expand this logic later to include WIndowSize and FlankLimit ). For example there might be 3 annotation files in the annotation directory. The annotation files are simple CSVs and in each annotation file there is a column with gene IDs. So if there are 2,3 and 5 colums in the files (one of which is the gene ID) the annotation table will show 7 columns of annotation information for each gene ((2+3+5) - 3).
## Tasks
- [x] Create/Include a annotations directory that we can put annotation files in (`~/.cob` or something)
- [x] Replace the subnet data in the subnetwork tab with information from the annotation tables

**Comment by monprin** [comment]
Should this be part of a grander project to integrate GWS into the site? Because it could be interesting results for both subnetworks in terms and custom network in the advanced query system, and I already have a fairly well refined way to handle these tables, not to mention all of the management stuff around it, so I will be borrowing code either way, but if we are going to wholly integrate GWS seamlessly, then I will approach it differently.

**Comment by monprin** [comment]
Okay FYI I went the full integration route, gene word search is now a dependency for COB, but I upgraded it such that we can now get out the words for each gene individually, so we can piggyback off of its handling of the databases completely, so I will simply query the folder, look for files with a specific pattern in the title (to denote species), feed them to gws and just query them at will.

Also now that it will essentially be in there anyway, I will add the functionality to quickly query gws for the significant annotations of a subnetwork in the polywas layout, or the entire custom network, after I finish the annotations in the table and the stuff to spruce the custom network graph.

**Comment by schae234** [comment]
So this feature is even simpler to what GWS does. GWS find significantly enriched words from a query set, I am just looking for gene annotations for genes that happened to get loaded in the network. 

You know the [raw database](https://github.com/monprin/geneWordSearch/blob/master/genewordsearch/databases/maize/raw/geneMatrix_v2.tsv) that GWS uses? Pull out the gene ids from that table as well as the "functional annotation" column (first and last colums). Load those annotations for each gene that gets loaded in the subnetwork table.

After we have gene annotations loaded, we will fully integrate GWS to make sure that annotations are statistically correct. Sometimes its just nice to get an idea of what the genes are doing as a gut check before you do enrichment.

**Comment by monprin** [comment]
That is what I am doing initially, I am just using the GeneWordSearch package since it is already  reasonably robust and fairly effectively handles parsing the table and getting rid of useless words, and then I don't have to keep a separate set of code that does the same effective thing. When I get it implemented you shouldn't be able to tell the back end is being handled by gws, it's just a way to make the code more maintainable and robust.

**Comment by schae234** [comment]
OK, but just to be clear, on first pass its not just words, it's the whole annotation? right? Like simply adding columns to the subnetwork table. Nothing fancy.

**Comment by monprin** [comment]
...it is now....

**Comment by schae234** [comment]
THEN WE WILL FANCY THE HELL OUT OF IT!

**Comment by monprin** [comment]
Done in #41, the folder for annotations can be defined by `COB_ANNOTATIONS` env variable, but defaults to `~/.cob/`. More details can be found in the README.
