### ISSUE TITLE
Sun Layout

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#3]
## Feature Description

After ordering genes based on genetic coordinate, layout genes that occur at the same locus outwards, sort of looking like the ray from the sun. This will add an additional dimension that we can distinguish genes on.

![screenshot from 2016-05-17 11 25 03](https://cloud.githubusercontent.com/assets/2566591/15330328/1097579e-1c22-11e6-97e2-26ccc5cc1d00.png)
## Tasks
- [x] Position genes outwards on a ray from the center of the circle
- [x] Order genes so that highest degree nodes are near the center
## Notes

Is it possible to play around with labels of both genes and chromosomes so that they are visible? Maybe so that they are positioned near the center of the circle?

**Comment by monprin** [comment]
Done with #10  looks better, but still needs other features for this to be especially useful.
