### ISSUE TITLE
Fix Arabidopsis Ontologies

### ISSUE THREAD

**Issue by monprin** [LinkageIO/cob#33]
Figure out why arabadopsis ontologies don't work and preferably fix them or at least remove them from the options.

**Comment by schae234** [comment]
You can remove them.

You should be able to do it with the camoco rm CLI command.

**Comment by monprin** [comment]
Do you know why they don't work? or why they don't appear to have any genes?

**Comment by schae234** [comment]
Nope, I have no idea. That Arabidopsis branch is dead right now. Dont want it.

**Comment by monprin** [comment]
Okay.

**Comment by monprin** [comment]
Removed
