### ISSUE TITLE
Annotation overaly

### ISSUE THREAD

**Issue by MeeshCompBio** [LinkageIO/cob#60]
Is it possible to include the gene annotation when hovering over a gene in cob?

Thanks!

**Comment by monprin** [comment]
Well the problem with that is is that it has the potential to take up a lot of space, but I can play with putting a maximum char count on it or something

**Comment by MeeshCompBio** [comment]
Or even the ability to download an annotation file from a subset of selected genes?

**Comment by schae234** [comment]
If you scroll over to Annotation column in the Genes table, it'll show the annotation for clicked genes. You can download a CSV for all clicked genes using the convenient CSV button. It does however include rows for neighbors.

**Comment by MeeshCompBio** [comment]
Awesome, thanks!
