### ISSUE TITLE
Toggle to remove from graph

### ISSUE THREAD

**Issue by monprin** [LinkageIO/cob#63]
Look into the viability of having some sort of toggle to remove a given gene from the graph, the reverse of the add gene process. Possibly more of v1.1 thing, but we will see.

**Comment by monprin** [comment]
Done in #76

**Comment by schae234** [comment]
😶😶😶😶😶 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣
