### ISSUE TITLE
Visible neighbors option does not work with refresh graph button

### ISSUE THREAD

**Issue by MeeshCompBio** [LinkageIO/cob#64]
When trying to set the cob option "Visible Neighbors (For Custom)" to 0, the network still displays neighbors if the "refresh graph" button is used. If I use the "build graph" button on the network tab, then it works.

**Comment by schae234** [comment]
Sounds like a event bug or is that the expected behavior? @monprin?

**Comment by monprin** [comment]
Was a logic bug, fixed in next version.
