### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#7]
## Description

Organize the different tables we currently have into tabs.
## Tasks
- [x] Look for possible tab `js` lib (bootstrap) or salvage code from the original COB base.
- [x] Implement some sort of walkthrough to fix the weird ordering issue (select x then y).
## Notes

In the orginal COB we had:
- Main (could be where the SNP to gene mapping is)
- Genes
- Interactions
- Options (visual style etc)

How hard would it be to do the div highlighting that some sites do? Where it highlights areas and is like, "click here to set X", etc.

**Comment by monprin** [comment]
Tabs added in #12, styling could be tweaked, but it is different enough at this point to warrant a new issue I believe. Basic mechanics work well and are very easy to augment.
