### ISSUE TITLE
Custom Network fails when there are no edges b/w query genes

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#70]
The server throws an attribute error. If I print out `nbs` from server.py line [320](https://github.com/schae234/cob/blob/51d34e43859360411c51082b37a2e4427cbed2f9/cob/server.py#L320) it says there is no gene_a.

Which is true when [camoco.COB.py:171](https://github.com/schae234/Camoco/blob/5ef4377175ad9bf2bc1e3e7390cf9966c2de46c5/camoco/COB.py#L171) gets returned.

**Comment by schae234** [comment]
Modified camoco.COB.py to return an empty index. Will be in an upcoming PR.

**Comment by schae234** [comment]
Holy shit. If you reference an issue in a commit message it handles it automatically for you... even across repos ...

![](https://media.giphy.com/media/yyvSeRGVj4C64/giphy.gif)

**Comment by monprin** [comment]
So this is all good now?

**Comment by schae234** [comment]
The fix worked for me. Can you test a query in one of your maize that has genes (the ids are in the network) however, all the genes global degrees are 0?
