### ISSUE TITLE
DataTables column headers do not scroll with columns

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#75]
In the "Genes" tab, when you scroll horizontally, the column headers stay in the same place and do not line up with their respective columns:

![image](https://cloud.githubusercontent.com/assets/2566591/22935939/a3173cc6-f299-11e6-83eb-9327d3ffd370.png)

**Comment by monprin** [comment]
Yeah I know It's on my list. 😂

**Comment by monprin** [comment]
Fixed in #76

**Comment by schae234** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣
